# Generated by Django 5.1.6 on 2025-05-12 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_question_questionattempt_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_seconds', models.FloatField(blank=True, null=True)),
                ('questions_count', models.IntegerField(default=5)),
                ('correct_count', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['total_seconds', '-end_time'],
            },
        ),
        migrations.CreateModel(
            name='TournamentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_questions', to='myapp.tournamentattempt')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('tournament', 'position')},
            },
        ),
    ]
